#!/usr/bin/env python

import getopt
import sys

from specGen import generator

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
	except getopt.GetoptError, err:
		print str(err)
		usage()
		sys.exit(2)
	
	for option, value in opts:
		if option in ("-h", "--help"):
			usage()
			sys.exit()
		else:
			assert False, "Unhandled option"
	
	if len(args) >= 2:
		gen = generator.generator()
		input = file(args[0], "r")
		output = file(args[1], "w")
		gen.process(input, output)
	else:
		print "spec-gen expects two arguments"
		usage()
		sys.exit(2)

def usage():
	print """Umm, yeah. You use this."""

if __name__ == "__main__":
	import cProfile, pstats, os
	cProfile.run('main()', "spec-gen.foobar.stat")
	stat = pstats.Stats("spec-gen.foobar.stat")
	stat.sort_stats("time")
	stat.print_stats()
	os.remove("spec-gen.foobar.stat")
	#main()